### ISSUE TITLE
Proposal Issue Template Proposal

### ISSUE THREAD

**Issue by will-nemo** [oneleif/olWebsite-React#131]
### Summary

It seems with any upcoming oneleif projects there will need to be certain items open source teams will need to discuss and decide on. One way to keep track (and something we've discussed before) is the use of of proposals to bring up discussions for projects. 

These proposals will cover items such as code styling/standards, styling standards, test standards, and tools utilized by the project. Having a system where we can make proposals and the team can discuss and then make decisions will keep everyone on the same page and have a standard to reference when doing peer review of pull requests.

### Example 
An example of how proposals would be written up is exactly how this proposal is being down now. I have a title that is specific and direct. A couple paragraphs discussing the problem and what needs to be solved. This fine example and then the rough idea (as shown below).

### Implementation
This would be the template we would provide to members looking to make a proposal. Resource found here: https://github.com/immersive-web/proposals/blob/master/ProposalsIssueTemplate.md

***

# Template
### Title
Just enough information to be specific and memorable.

### Summary
One or two paragraphs listing the problem being solved and the target audience for the idea.

### Example use cases
Two or three examples of an end user with goals and a step-by-step description of how the proposed idea solves helps them achieve the goal.

### A rough idea or two about implementation
One or two paragraphs about how the feature might be implemented, mostly to help clarify how you're thinking about the problem space and the underlying technologies that could solve the problems.

**Comment by ambid17** [comment]
Looks good to me

**Comment by ambid17** [comment]
Heres the checklist we currently have:
- create a github repo
- make a wiki for the project, with an MVP (at the very least a list of features, with a little explanation of each)
- start making tickets that others can work on
- choose coding standards
- choose contribution standards (how to make tickets, issues, what branches to use, etc)… you can link to the oneleif contribution standards/guides
- add a readme explaining the project and what you expect from contributors/your team
- add oneleif footer to the readme
- find a team!
