### ISSUE TITLE
Close Mobile Navigation once link clicked

### ISSUE THREAD

**Issue by will-nemo** [oneleif/olWebsite-React#146]
Right now when a link is clicked in the navigation overlay in the mobile view the navigation stays open. Will need the overlay to close

**Comment by b1995** [comment]
I was thinking maybe it would be useful to make clicking anywhere outside the navbar close the navigation overlay, too. What do you guys think?

**Comment by will-nemo** [comment]
> I was thinking maybe it would be useful to make clicking anywhere outside the navbar close the navigation overlay, too. What do you guys think?

The new overlay being designed show take up the entire view so i think that functionality but be unnecessary at this point
