### ISSUE TITLE
Code Standards: Javascript Functions Documentation Proposal

### ISSUE THREAD

**Issue by will-nemo** [oneleif/olWebsite-React#154]
### Summary

Currently our jsdocs seem to be off a bit. The way we have it formatted doesn't allow the ide's to give us the full functionality possible. The way I'm proposing is provided by jsdocs and seems to be the right way to do it.

### Example

https://jsdoc.app/tags-returns.html
[This pr](https://github.com/oneleif/olWebsite-React/issues/131) uses the docs this way; pull it up in your ide and you can see how it works.

### Implementation

```
/**
 * Returns the sum of a and b
 * @param {number} a
 * @param {number} b
 * @returns {number}
 */
```

**Comment by ambid17** [comment]
looks good to me

**Comment by Fabricevladimir** [comment]
Agreed.
