### ISSUE TITLE
Initiatives is spelt incorrectly

### ISSUE THREAD

**Issue by 0xLeif** [oneleif/olWebsite-React#240]
> Our projects are as diverse as our members. From open source initiatitves to personal experiments, we’ve got it all.

Should be

> Our projects are as diverse as our members. From open source initiatives to personal experiments, we’ve got it all.

**Comment by Gautam-Arora24** [comment]
Can I solve this issue?

**Comment by 0xLeif** [comment]
@Gautam-Arora24 That would be awesome!! 😄

**Comment by 0xLeif** [comment]
Resolved in #241
