### ISSUE TITLE
Create View for log in

### ISSUE THREAD

**Issue by will-nemo** [oneleif/olWebsite-React#244]
https://www.figma.com/file/zukLdUXgDYBhPAU8NZbljW/OL-Website-Workspace?node-id=414%3A2

Based off the designs in figma under sign up and login flow create the view for logging the user in. Should use the existing inputs and buttons from the oneleif components.

At this point this needs no functionality, just the view

**Comment by lubomirrozhon** [comment]
Hi, can you assign me this ?
