### ISSUE TITLE
Update contact phone number

### ISSUE THREAD

**Issue by 0xLeif** [oneleif/olWebsite-React#257]
On the contacts page the phone number should be updated to +1 (531) 207-7377

https://dev.oneleif.com/contact

https://oneleif.com/contact

**Comment by akaash11** [comment]
Hey, i would like to work on this issue

**Comment by akaash11** [comment]
Hey @0xLeif  can you please do this,

> Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate. Alternatively, an individual PR can be opted-in with a maintainer adding the "hacktoberfest-accepted" label to the PR.

Can you please do the needful?

**Comment by 0xLeif** [comment]
@akaash11 done!
