### ISSUE TITLE
ci: Add issue templates

### ISSUE THREAD

**Issue by aayushchugh** [oneleif/olWebsite-React#280]
currently there are no issue templates in this repo
I think we should add some

here is example of issue templates I can add in this repo:-
https://github.com/shriproperty/server/issues/new/choose

**Comment by 0xLeif** [comment]
@aayushchugh Greate suggestion! I agree, we should add some! I'll work on this when I have some extra time. Thank you for contributing.

**Comment by aayushchugh** [comment]
@0xLeif I can do this for you now please assign this issue to me

**Comment by aayushchugh** [comment]
@0xLeif I have created the [pr](https://github.com/oneleif/olWebsite-React/pull/281) please check that out
