### ISSUE TITLE
Update additional dependencies and remove unneccessary ones.

### ISSUE THREAD

**Issue by Azoraqua** [oneleif/olWebsite-React#289]

**Comment by aayushchugh** [comment]
Dependences which can be replaced by MUI

- react-hamburger-menu -> [MUI Drawer](https://mui.com/material-ui/react-drawer/#main-content) 
- react-icons -> [MUI Icons](https://mui.com/material-ui/material-icons/#main-content)
- react-responsive -> MUI is already responsive

**Comment by Azoraqua** [comment]
I am aware.
