### ISSUE TITLE
Make the header dynamic based on authentication

### ISSUE THREAD

**Issue by ambid17** [oneleif/olWebsite-React#31]
The header should show, for example "dashboard" when a user is logged in, but not when they are logged out.

**Comment by jajiskoot** [comment]
are we going by the figmas where it shows the person icon on the right? or with a "dashboard" tab like you said?

**Comment by will-nemo** [comment]
> are we going by the figmas where it shows the person icon on the right? or with a "dashboard" tab like you said?

When a user is logged in we will show the user icon, don't know much about the "dashboard" but that can always be added later when we actually implement a dashboard. I don't know if that's on the MVP roadmap
