### ISSUE TITLE
Search Box Validation

### ISSUE THREAD

**Issue by will-nemo** [oneleif/olWebsite-React#37]
Will need to show some sort of message when an empty string has been entered into the search box that will prompt the user to enter a value

**Comment by Fabricevladimir** [comment]
Is it necessary to show a message? It might be best to just not perform a search with an empty string.

**Comment by zmeriksen** [comment]
What is the different from "" and "       "

- Are they both empty?
- Does one search and one doesn't?

**Comment by Fabricevladimir** [comment]
Although the input can contain those spaces, we can call the search handler with trimmed values so both would end up being empty and not searched.

**Comment by zmeriksen** [comment]
I'm indifferent to if we show an error or not... You might want to check with @suzyfendrick 

I think for ADA/ other reasons, showing an error would be useful.

**Comment by suzyfendrick** [comment]
Maybe it just won't let you search until you type something? So the search icon is disabled for use until they type in something. And if they hit the enter to search then an error message pops up? Or nothing happens.
