### ISSUE TITLE
File Naming Convention Proposal

### ISSUE THREAD

**Issue by will-nemo** [oneleif/olWebsite-React#42]
### React Component File naming:
   
- Should be contained in Folders that are in PascalCase

- Should have .jsx extenstion on files that contain React/JSX

- Should be written in PascalCase

Example:
 (contained in src/components/MyComponent/MyComponent.jsx)
```MyComponent.jsx```

**Reason: These are the most common naming conventions when it comes to react**

### Javascript File naming:
   
- Should be contained in Folders that are in kebab-case

- Should have .js extenstion on files that contain strictly Javascript

- Should be written in kebab-case

Example:
 (contained in src/components/compent-utils/component-utils.js)
```component-utils.js```

**Reason: These are the most common naming conventions when it comes to javascript that I've worked with**

**Comment by will-nemo** [comment]
https://google.github.io/styleguide/jsguide.html#file-name

**Comment by ambid17** [comment]
As long as the folder structure is of quality, we can keep PascalCase for all file types for consistency

**Comment by will-nemo** [comment]
> As long as the folder structure is of quality, we can keep PascalCase for all file types for consistency

Usually PascalCase indicates React is being used in that file or folder, but I am a fan of consistency.
I would usually have the js files living inside the folder of the react component
```
src/component/MyComponent/js/component-utils/component-utils.js
```

**Comment by Fabricevladimir** [comment]
@will-nemo While I like how modularized that makes each component, this might end up with very long paths if two components share one utility function for whatever reason. Plus, you'll end up with a bunch of component-utils folders, and that might get a little confusing in the editor. I think dropping the js files in one utils folder might help reduce the number of folders generated as well.

**Comment by will-nemo** [comment]
> @will-nemo While I like how modularized that makes each component, this might end up with very long paths if two components share one utility function for whatever reason. Plus, you'll end up with a bunch of component-utils folders, and that might get a little confusing in the editor. I think dropping the js files in one utils folder might help reduce the number of folders generated as well.

this was just a quick example, I'm also a fan of a utils folder too

**Comment by ambid17** [comment]
well, looks like we are all in agreeance on this as long as there's a utils folder added to the proposal :D
