### ISSUE TITLE
React Function Styling Proposal

### ISSUE THREAD

**Issue by will-nemo** [oneleif/olWebsite-React#43]
### Declaring Functions with keyword 'function'

**The Debate:**
When writing with React I've seen two different approaches to writing functions
```
const update = () => {

}
```
&&
```
function update() {

}
```

**Proposal:**
To use the latter function that uses the keyword function

**Reason: Easier to scan component for functions, especially with a large file. These functional components all start to look the same and this will help functions stand out**

**Comment by ambid17** [comment]
I second this solely because there are so many different levels of arrow functions that allows you to take out "return", extra parentheses, etc, depending on the conditions. I think the normal function syntax keeps things consistent
