### ISSUE TITLE
IF statement Styling Convention Proposal

### ISSUE THREAD

**Issue by will-nemo** [oneleif/olWebsite-React#44]
**When writing if/else if/else statements**

- statements are on their own line

- spacing between if and bracket

```
if (/*logic*/) {
   //perform action
}
else if (/*logic*/) {
   //perform action
}
else {
   //perform action
}
```

- nested if statements are tabbed over as such

```
if (/*logic*/) {
    if (/*logic*/) {
       //perform action
    }
}
```

**Reason: Allows for code readability and looks very clean; which is very important when trying to have a large group of people working on the same code base**

**Comment by ambid17** [comment]
i second the motion
