### ISSUE TITLE
HTML/CSS/JS naming conventions

### ISSUE THREAD

**Issue by will-nemo** [oneleif/olWebsite-React#45]
### HTML Naming Conventions

**Naming Style of ids**

- id should be in camelCase

- Example `id="fakeId`

**Reason: most common convention and will make the id look different from classNames**

### CSS Naming Conventions

**Naming Style of class names**

- class name should be in kebab-case

- Example `className="fake-idd`

**Reason: most common convention, able to tab between each word in a CSS file,  Also, using hyphens allows you to take advantage of the |= attribute selector, which selects any element containing the text, optionally followed by a dash:**

`span[class|="em"] { font-style: italic; }`

### Javascript Naming Conventions

**Naming Style of class names**

- variables should be in camelCase

- variables should be descriptive, avoid shortening names to keep names informative

- Example `let exampleName;` instead of `let exName;`

**Reason: With a large code base and hope to have a lot of devs, having descriptive names with help newer and younger devs know what's going on**

**Naming Style of constants**

- constants should be all caps

- constants should have underscores to delimit spaces

- Example `const EXAMPLE_CONSTANT = "example";` instead of `const exampleConstant = "example";`

**Reason: makes constants identifiable and readable, gives a good description of what they are or what they're used for**

**Comment by ambid17** [comment]
please add a second example to the JavaScript Naming Conventions:
Example ` let exampleName` instead of `let exName`
