### ISSUE TITLE
React File Format Proposal

### ISSUE THREAD

**Issue by will-nemo** [oneleif/olWebsite-React#47]
- The use of functional components instead of class components

- using the keyword function and default export on same line

- imports at top of page (whitespace between different types of imports)

- constants above component 

- useState at top of component

-  useEffects under useState

- functions under useEffects

- render at the bottom of the page

**Example:**

```
import React, { useState, useEffect } from "react";

import Example from "example";

  /************************************
   * Constants
   ************************************/

  const EXAMPLE_CONST = "example const";

export default function ExampleComponent() {
  /************************************
   * State
   ************************************/

  const [exampleState, setExampleState = useState();

  /************************************
   * Life Cycle Hooks
   ************************************/

   useEffect(() => {

   }, []);

  /************************************
   * Functions
   ************************************/
  
   function exampleFunction() {

   }

  /************************************
   * Render
   ************************************/

  return (
    <div>
    </div>
  );
};
```

**Reason: Using the function instead of the es6 method allows everything (parameters and export)  to be on one line and helps the functional component stand out more. Life cycle at the top allows to see the actions performed on useEffect quickly and easily. Render at the bottom keeps a uniform file and no other reason lol**

**Comment by ambid17** [comment]
looks perfect, great example

**Comment by arkus7** [comment]
How about converting it into a wiki page?
