### ISSUE TITLE
JS Docs Proposal

### ISSUE THREAD

**Issue by will-nemo** [oneleif/olWebsite-React#48]
### Function Documentation

**Above each function**

```
/**
* Description of function goes here
*
* @param {<Type of Param>} <Name of Param> - <Description of Param>
* @returns {<Type of Returns>} <Name of Returns> - <Description of Returns>
*/
```

**Reason: Classic JS docs, i think it's self explanatory**

### State Documentation

**Above each state**

```
/**
* Description of state goes here
*
* @type <Type of state>
* @default <default value if there is one>
*/
```

**Reason: i think it's self explanatory**

**Comment by ambid17** [comment]
there should be no argument here, this is already fairly standard
