### ISSUE TITLE
Handle User Authentication on Login/ Logout

### ISSUE THREAD

**Issue by will-nemo** [oneleif/olWebsite-React#72]
Currently on a successful user login the user is redirected to the landing view. Before this occurs we will need to take the user credentials off the response header and store them in the window. These values will be the user email, the session token and the expiration date the session tokens

When the user logs out, we also need to make sure that all previously saved authentication information is removed.

**Comment by Fabricevladimir** [comment]
Why not keep it in local storage?

**Comment by jajiskoot** [comment]
local storage is insecure. not that we're really dealing with important info but all the same best to keep user info secure

**Comment by jajiskoot** [comment]
But I set it up just for us to use it for now because the alternative of cookies and server stuff is more complicated
